# Generated by Django 5.0 on 2024-01-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='is_completed',
            new_name='is_Completed',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskDescription',
            new_name='task_Description',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskTitle',
            new_name='task_Title',
        ),
    ]
