# Generated by Django 5.0 on 2024-01-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='category',
        ),
    ]
